image: ghcr.io/zephyrproject-rtos/ci:v0.29.3
stages:
  - build
  - package-artifacts

variables:
  DEBIAN_FRONTEND: noninteractive
  ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains

build:
  stage: build
  script:
    - west init -l espi-debugger
    - west update
    - west zephyr-export
    - git clone --depth 1 https://github.com/MicrochipTech/CPGZephyrDocs.git
    - cp CPGZephyrDocs/MEC172x/SPI_image_gen/mec172x_spi_gen_lin_x86_64 .
    - export MEC172X_SPI_GEN=$PWD/mec172x_spi_gen_lin_x86_64
    - west build -p always -b mec172xevb_assy6906 espi-debugger

  artifacts:
    paths:
      - build/zephyr/zephyr*
      - build/zephyr/*.bin